### ISSUE TITLE
Kernel Panic when performing soft reboot

### ISSUE THREAD

**Issue by aviraxp** [aviraxp/ONEPLUS_MSM8994_KAWORI#1]
<6>[20170514_00:45:44.932035]@0 ------------[ cut here ]------------
<2>[20170514_00:45:44.932056]@0 Kernel BUG at ffffffc000437680 [verbose debug info unavailable]
<0>[20170514_00:45:44.932066]@0 Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
<6>[20170514_00:45:44.932089]@0 Modules linked in: wlan(C) qdrbg_module qcrypto_module
<6>[20170514_00:45:44.932100]@0 CPU: 0 PID: 1 Comm: init Tainted: G         C   3.10.84-perf #1
<6>[20170514_00:45:44.932108]@0 Hardware name: Qualcomm Technologies, Inc. MSM8994v2.1 MTP (DT)
<6>[20170514_00:45:44.932117]@0 task: ffffffc01027d000 ti: ffffffc010288000 task.ti: ffffffc010288000
<6>[20170514_00:45:44.932137]@0 PC is at power_on_l2_msm8994+0x208/0x25c
<6>[20170514_00:45:44.932147]@0 LR is at power_on_l2_msm8994+0x1f4/0x25c
<6>[20170514_00:45:44.932155]@0 pc : [<ffffffc000437680>] lr : [<ffffffc00043766c>] pstate: 60000145
<6>[20170514_00:45:44.932163]@0 sp : ffffffc01028bbc0
<6>[20170514_00:45:44.932176]@0 x29: 0000007ff319ac90 x28: 0000000000000005 
<6>[20170514_00:45:44.932189]@0 x27: ffffffc0c183c000 x26: ffffffc00128ebc8 
<6>[20170514_00:45:44.932201]@0 x25: 0000000000000005 x24: 0000000000000005 
<6>[20170514_00:45:44.932213]@0 x23: ffffffc0c62727b8 x22: ffffff800063a00c 
<6>[20170514_00:45:44.932227]@0 x21: 0000000000000000 x20: ffffff8000634000 
<6>[20170514_00:45:44.932239]@0 x19: ffffff800063a000 x18: 0000007facc4af50 
<6>[20170514_00:45:44.932252]@0 x17: 0000007facb7fc64 x16: 0000007facc39bf8 
<6>[20170514_00:45:44.932265]@0 x15: 0000007facc39000 x14: 0000000000000000 
<6>[20170514_00:45:44.932277]@0 x13: 0000007facc47000 x12: 0000000000000000 
<6>[20170514_00:45:44.932290]@0 x11: 0101010101010101 x10: 0000000000003ebf 
<6>[20170514_00:45:44.932302]@0 x9 : ffffffc01028b930 x8 : ffffffc01027d580 
<6>[20170514_00:45:44.932314]@0 x7 : ffffffc010288000 x6 : ffffffc0c2980000 
<6>[20170514_00:45:44.932326]@0 x5 : 0000000000000000 x4 : 0000000000000000 
<6>[20170514_00:45:44.932339]@0 x3 : 0000000000000140 x2 : 000000000000c7d7 
<6>[20170514_00:45:44.932352]@0 x1 : 0000000000000000 x0 : 00000000702f302e 
<6>[20170514_00:45:44.932359]@0 
<0>[20170514_00:45:44.932367]@0 Process init (pid: 1, stack limit = 0xffffffc010288058)
<6>[20170514_00:45:44.932375]@0 Call trace:
<0>[20170514_00:45:44.932386]@0 Code: 72103c1f 54fffd00 710006b5 54ffff21 (e7f001f2) 
<4>[20170514_00:45:44.932395]@0 ---[ en

**Comment by aviraxp** [comment]
Call trace missing.......

**Comment by aviraxp** [comment]
One commit hit this again everty time after the voltage commit, but I could not find out which.

**Comment by aviraxp** [comment]
This seems to be a common panic and I

**Comment by aviraxp** [comment]
I finally address it. This is caused by Boeffla config app. I removed some useful ramdisk part and causes the script hang.

**Comment by aviraxp** [comment]
The issue is this commit: "soc: qcom: cpu_ops: fix scope bug for 8994 'timeout' variable"

It is fine, but it hits a bug in core_ctl module, where the timeout value got reused and hit timeout.

**Comment by zachariasmaladroit** [comment]
>The issue is this commit: "soc: qcom: cpu_ops: fix scope bug for 8994 'timeout' variable"
>
>It is fine, but it hits a bug in core_ctl module, where the timeout value got reused and hit timeout.

I seem to hit this issue, too, after applying that change

thanks for tracking the source down !
