### ISSUE TITLE
swapoff hungs and prevent suspend

### ISSUE THREAD

**Issue by aviraxp** [aviraxp/ONEPLUS_MSM8994_KAWORI#3]
swapoff cannot be freezed, even on stock kernel when swap is enabled. I disable swap for this reason.

**Comment by zachariasmaladroit** [comment]
@aviraxp what do you mean with swapoff in that context ? why is there a need for disabling of swap before suspending ?

in any case if you haven't, take a look at the changes for swap.c , swapfile.c and swap_state.c in my repo

https://github.com/zachariasmaladroit/android_kernel_sony_msm8994_kitakami_r2/commits/Sun-Kernel_Facula_I.2/mm/

perhaps besides the zram, zsmalloc changes there's anything useful which would help

also: raising page-cluster (e.g. to 16) helps to reduce i/o and other stalls

**Comment by aviraxp** [comment]
swapoff is a binary in busybox. When system is suspending, it cannot be freezed.

**Comment by aviraxp** [comment]
zram init.sh issue.

**Comment by aviraxp** [comment]
finally fixed by https://github.com/aviraxp/ONEPLUS_MSM8994_KAWORI/commit/eaf804e4f934cb372c9f342515c3ea00bc6d3993. Fuck you CAF!
